---
- 
  hosts: localhost
  gather_facts: false
  become_user: root

  tasks:
   - 
     name: Run app
     shell: 'forever start /home/DevOps/main.js 3333'
     ignore_errors: true
   - 
     name: Security- Check if latest package version
     apt:
      name: ['bash', 'openssl','openssh-client', 'openssh-server']
      state: latest
     ignore_errors: true

   - 
     name: Concept-Remove contents of temp folder
     file:
      path: '/tmp/'
      state: '{{item}}'
     with_items:
      - absent
      - directory
     ignore_errors: true
     become: yes
